### ISSUE TITLE
Training on Mapillary VISTAS?

### ISSUE THREAD

**Issue by brucemuller** [elnino9ykl/ERF-PSPNet#2]
Hello!

I'm having some trouble getting sensible results on Vistas.

Did you get reasonable results on this dataset? 

Bruce

**Comment by elnino9ykl** [comment]
Hi, 
please check this video:
https://events.infovaya.com/presentation?id=40338
which is trained with Mapillary VISTAS. 
Our ERF-PSPNet reaches a mIoU of 54.3% using 27 classes at the resolution of 1024x512.
As VISTAS contains many less frequent classes, it is suggested to cut some classes and train a bit longer to get reasonable results.

**Comment by brucemuller** [comment]
Hi @elnino9ykl 

That's great, thanks for your reply. Will your paper be available soon? I'd like to read it. 

Cutting the classes is sensible though I'm intending to compare with Mapillary's result and won't be easily able to in that case. Do you know how Mapillary deal with the class imbalance?

**Comment by elnino9ykl** [comment]
Hi, actually I don't know how Mapillary deals with the class imbalance problem.
You could use Focal Loss (already implemented in my code) for training, which is helpful for improving the accuracy of less frequent classes.
I checked other papers that use Mapillary for training, and some of them have also cut some classes.
Our paper will be available soon. Thank you very much for your interest.

**Comment by brucemuller** [comment]
@elnino9ykl thanks for your reply... I'll give focal loss a go. Can you reference any paper(s) which use the smaller number of Vistas classes?

Also, you mentioned geometric augmentation in your readme. Where about is it in your code?
I'd like to do some augmentation, including rotation and reflect for the missing pixels but couldn't find out how.

**Comment by elnino9ykl** [comment]
Hi,

I have read this paper, which uses 7 classes:
https://arxiv.org/pdf/1904.01886.pdf
DADA: Depth-aware Domain Adaptation in Semantic Segmentation

In our previous works (http://www.robesafe.uah.es/personal/bergasa/papers/icves2018.pdf),
we use 27 classes, which we think are important for navigation assistance applications.
The 27 classes include pole, street light, billboard, traffic light, car, truck, bicycle, motorcycle,
bus, traffic sign front, traffic sign back, road, sidewalk, curb-cut, crosswalk-plain, bike-lane, 
curb, fence, wall, building, person, rider (motorcyclist, bicyclist), sky, vegetation, 
terrain, general road marking, and crosswalk zebra.

The augmentation code is in the 
https://github.com/elnino9ykl/ERF-PSPNet/blob/master/train/main.py:

if(self.augment):
            # Random hflip
            hflip = random.random()
            if (hflip < 0.5):
                input = input.transpose(Image.FLIP_LEFT_RIGHT)
                target = target.transpose(Image.FLIP_LEFT_RIGHT)

            degree=random.randint(-20,20)
            input=input.rotate(degree,resample=Image.BILINEAR,expand=True)
            target=target.rotate(degree,resample=Image.NEAREST,expand=True)

            w, h=input.size
            nratio=random.uniform(0.5,1.0) 
            ni=random.randint(0,int(h-nratio*h))
            nj=random.randint(0,int(w-nratio*w))
            input=input.crop((nj,ni,int(nj+nratio*w),int(ni+nratio*h)))
            target=target.crop((nj,ni,int(nj+nratio*w),int(ni+nratio*h)))
            input=Resize((480,640),Image.BILINEAR)(input)
            target=Resize((480,640),Image.NEAREST)(target)

**Comment by brucemuller** [comment]
Thanks @elnino9ykl that's helpful, I appreciate your taking the time to reply :)
