### ISSUE TITLE
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [4, 976]

### ISSUE THREAD

**Issue by xuxiuzhi2627** [elnino9ykl/ERF-PSPNet#3]
RuntimeError: 1only batches of spatial targets supported (non-empty 3D tensors) but got targets of size: : [4, 976],could you help me to solve the problem?

**Comment by elnino9ykl** [comment]
Hi,
   Thank you for your question.
   Maybe you could check whether your target dataset (labels) is composed of grayscale images.
