### ISSUE TITLE
Did you use a custom dataset to train ERF-PSPNet?

### ISSUE THREAD

**Issue by khgapa** [elnino9ykl/ERF-PSPNet#4]
In your code(train/cityscapes/helpers/labels.py), the labels are different from the original cityscapes dataset.
Did you use a custom dataset to train and test the ERF-PSPNet?
If not, did you manually re-annotate the cityscape dataset?
I'd like to ask you about the dataset you used

**Comment by elnino9ykl** [comment]
Yes. We did select or reconfigure the classes using the datasets as described in the paper, for our desired application for helping visually impaired people. For example, in the PASS paper (http://www.robesafe.com/personal/bergasa/papers/IEEE_T_ITS_Kailun_2019_FINAL%20VERSION.pdf), we use the classes from Mapillary Vistas as shown in Table I.

**Comment by elnino9ykl** [comment]
For Cityscapes training, you can also refer to RFNet, which provides the exact 19 classes
https://github.com/AHupuJR/RFNet
